// ─────────────────────────────────────────────────────────────
// ROAR — Central Mock Data
// Single source of truth for all pages. Import from here only.
// ─────────────────────────────────────────────────────────────

export const MOCK_RESEARCH = [
  {
    id: 'roar-2025-soe-001',
    callNumber: 'APC-2025-SOE-001',
    title: 'Tidal Energy Systems in Philippine Waters',
    authors: ['Dr. Maria Santos'],
    department: 'SOE',
    program: 'BS Civil Engineering',
    year: 2025,
    views: 341,
    status: 'Published',
    keywords: ['tidal energy', 'renewable energy', 'Philippines', 'ocean engineering'],
    abstract:
      'This study investigates the feasibility and output potential of tidal energy conversion systems deployed along key tidal channels in the Philippine archipelago. Hydrodynamic modeling and in-situ measurements from 2023–2024 reveal peak energy densities sufficient for community-scale microgrid deployment.',
    submittedBy: 'facrep.cs@apc.edu.ph',
    submittedDate: '2025-03-14',
    archivedDate: '2025-03-20',
  },
  {
    id: 'roar-2024-SOM-001',
    callNumber: 'APC-2024-SOM-001',
    title: 'AI-Assisted Diagnosis in Rural Healthcare',
    authors: ['Dr. Jose Reyes', 'Dr. Grace Ong'],
    department: 'SOM',
    program: 'BS Business Administration',
    year: 2024,
    views: 278,
    status: 'Published',
    keywords: ['artificial intelligence', 'healthcare', 'rural medicine', 'diagnostics'],
    abstract:
      'We evaluate the performance of a lightweight convolutional neural network model for preliminary disease classification in low-connectivity rural healthcare settings. Using a dataset of 12,000 clinical images collected from partner barangay health centers, the model achieves 87% sensitivity for the top-three disease categories.',
    submittedBy: 'facrep.cs@apc.edu.ph',
    submittedDate: '2024-11-05',
    archivedDate: '2024-11-12',
  },
  {
    id: 'roar-2025-socit-001',
    callNumber: 'APC-2025-SOCIT-001',
    title: 'Blockchain for Academic Credential Verification',
    authors: ['Prof. Ana Cruz'],
    department: 'SOCIT',
    program: 'BS Computer Science',
    year: 2025,
    views: 211,
    status: 'Published',
    keywords: ['blockchain', 'credentials', 'academic integrity', 'distributed ledger'],
    abstract:
      'A permissioned blockchain prototype is designed and benchmarked for academic transcript and diploma verification among Philippine Higher Education Institutions. Transaction throughput and tamper-evidence properties are evaluated against existing centralized registry approaches.',
    submittedBy: 'facrep.cs@apc.edu.ph',
    submittedDate: '2025-01-18',
    archivedDate: '2025-01-25',
  },
  {
    id: 'roar-2024-soe-002',
    callNumber: 'APC-2024-SOE-002',
    title: 'Sustainable Urban Agriculture in Metro Manila',
    authors: ['Dr. Luis Tan'],
    department: 'SOE',
    program: 'BS Environmental Engineering',
    year: 2024,
    views: 198,
    status: 'Published',
    keywords: ['urban farming', 'sustainability', 'Metro Manila', 'food security'],
    abstract:
      'This paper examines the scalability of rooftop and vertical farming systems in high-density urban barangays within Metro Manila. Yield-per-square-meter, water consumption, and economic viability across six pilot sites are compared against traditional community garden models.',
    submittedBy: 'facrep.cs@apc.edu.ph',
    submittedDate: '2024-09-22',
    archivedDate: '2024-09-30',
  },
  {
    id: 'roar-2026-socit-002',
    callNumber: 'APC-2026-SOCIT-002',
    title: 'Cybersecurity Risk Assessment for MSMEs',
    authors: ['Prof. Carlo Lim'],
    department: 'SOCIT',
    program: 'BS Information Technology',
    year: 2026,
    views: 174,
    status: 'Published',
    keywords: ['cybersecurity', 'MSME', 'risk assessment', 'information security'],
    abstract:
      'A structured risk assessment framework tailored for micro, small, and medium enterprises in the Philippines is proposed and validated through a survey of 148 MSMEs in Metro Manila. The framework identifies critical control gaps and maps them to ISO/IEC 27001 controls with MSME-appropriate implementation guidance.',
    submittedBy: 'facrep.cs@apc.edu.ph',
    submittedDate: '2026-02-10',
    archivedDate: '2026-02-17',
  },
  {
    id: 'roar-2025-som-002',
    callNumber: 'APC-2025-som-002',
    title: 'Machine Learning in Financial Fraud Detection',
    authors: ['Dr. Grace Ong'],
    department: 'SOM',
    program: 'BS Accountancy',
    year: 2025,
    views: 132,
    status: 'Published',
    keywords: ['machine learning', 'fraud detection', 'fintech', 'anomaly detection'],
    abstract:
      'This study applies ensemble learning methods — Random Forest, XGBoost, and Isolation Forest — to transaction datasets from a Philippine digital payments provider for real-time fraud detection. Models are evaluated on precision, recall, and latency constraints suitable for production deployment.',
    submittedBy: 'facrep.cs@apc.edu.ph',
    submittedDate: '2025-06-03',
    archivedDate: '2025-06-11',
  },
  {
    id: 'roar-2024-soe-003',
    callNumber: 'APC-2024-SOE-003',
    title: 'Smart Grid Integration in Barangay Microgrids',
    authors: ['Engr. Paolo Delos Reyes'],
    department: 'SOE',
    program: 'BS Electrical Engineering',
    year: 2024,
    views: 118,
    status: 'Published',
    keywords: ['smart grid', 'microgrids', 'barangay electrification', 'load balancing'],
    abstract:
      'A low-cost smart metering and load-balancing architecture is proposed for off-grid barangay microgrids powered by a mix of solar and diesel sources. Field trials in two Mindanao communities demonstrate a 23% reduction in diesel consumption and improved voltage stability.',
    submittedBy: 'facrep.cs@apc.edu.ph',
    submittedDate: '2024-07-15',
    archivedDate: '2024-07-22',
  },
  {
    id: 'roar-2026-socit-003',
    callNumber: null,
    title: 'Data Privacy Compliance for Higher Education Institutions',
    authors: ['Prof. Diana Reyes'],
    department: 'SOCIT',
    program: 'BS Computer Science',
    year: 2026,
    views: 97,
    status: 'Under Review',
    keywords: ['data privacy', 'RA 10173', 'HEI compliance', 'NPC'],
    abstract:
      'An audit framework for assessing compliance with the Philippine Data Privacy Act (RA 10173) among private higher education institutions is developed. Interviews with 12 HEI data protection officers reveal common compliance gaps related to consent management and data breach notification procedures.',
    submittedBy: 'facrep.cs@apc.edu.ph',
    submittedDate: '2026-08-01',
    archivedDate: null,
  },
  {
    id: 'roar-2023-soe-004',
    callNumber: 'APC-2023-SOE-004',
    title: 'Impact of K-12 on Engineering Curriculum',
    authors: ['Dr. Ramon Villanueva'],
    department: 'SOE',
    program: 'BS Mechanical Engineering',
    year: 2023,
    views: 84,
    status: 'Published',
    keywords: ['K-12', 'engineering education', 'curriculum reform', 'CHED'],
    abstract:
      'Five years after full K-12 implementation, this study evaluates its effect on first-year engineering student readiness across ten Philippine universities. Cohort performance data, faculty interviews, and CHED compliance records are triangulated to assess curriculum realignment outcomes.',
    submittedBy: 'facrep.cs@apc.edu.ph',
    submittedDate: '2023-05-20',
    archivedDate: '2023-05-27',
  },
  {
    id: 'roar-2026-socit-004',
    callNumber: null,
    title: 'AI Ethics and Governance in Philippine Government Agencies',
    authors: ['Prof. Ana Cruz', 'Prof. Carlo Lim'],
    department: 'SOCIT',
    program: 'BS Computer Science',
    year: 2026,
    views: 71,
    status: 'Under Review',
    keywords: ['AI ethics', 'AI governance', 'Philippine government', 'public policy'],
    abstract:
      'This paper reviews the state of AI adoption and ethical governance frameworks across ten Philippine national government agencies. Policy gaps are identified against the OECD AI Principles and the EU AI Act, and a locally-adapted governance model is proposed for the Philippine context.',
    submittedBy: 'facrep.cs@apc.edu.ph',
    submittedDate: '2026-09-05',
    archivedDate: null,
  },
];

export const MOCK_REPRESENTATIVES = [
  { id: 'rep-001', name: 'Prof. Ana Cruz', department: 'SOCIT', program: 'BS Computer Science', email: 'ana.cruz@apc.edu.ph', status: 'Active', since: '2024-06-01' },
  { id: 'rep-002', name: 'Prof. Carlo Lim', department: 'SOCIT', program: 'BS Information Technology', email: 'carlo.lim@apc.edu.ph', status: 'Active', since: '2024-06-01' },
  { id: 'rep-003', name: 'Dr. Maria Santos', department: 'SOE', program: 'BS Civil Engineering', email: 'maria.santos@apc.edu.ph', status: 'Active', since: '2023-08-15' },
  { id: 'rep-004', name: 'Engr. Paolo Delos Reyes', department: 'SOE', program: 'BS Electrical Engineering', email: 'paolo.delosreyes@apc.edu.ph', status: 'Active', since: '2023-08-15' },
  { id: 'rep-005', name: 'Dr. Jose Reyes', department: 'SOM', program: 'BS Business Administration', email: 'jose.reyes@apc.edu.ph', status: 'Active', since: '2024-01-10' },
  { id: 'rep-006', name: 'Dr. Grace Ong', department: 'SOM', program: 'BS Accountancy', email: 'grace.ong@apc.edu.ph', status: 'Active', since: '2024-01-10' },
  { id: 'rep-007', name: 'Prof. Diana Reyes', department: 'SOCIT', program: 'BS Data Science', email: 'diana.reyes@apc.edu.ph', status: 'Active', since: '2025-06-01' },
  { id: 'rep-008', name: 'Dr. Luis Tan', department: 'SOE', program: 'BS Mechanical Engineering', email: 'luis.tan@apc.edu.ph', status: 'Inactive', since: '2022-08-01' },
];

export const MOCK_MATERIALS = MOCK_RESEARCH.map((r) => ({
  id: r.id,
  title: r.title,
  authors: r.authors,
  department: r.department,
  callNumber: r.callNumber,
  status: r.callNumber ? (r.status === 'Published' ? 'Archived' : 'Pending') : 'Pending',
  submittedDate: r.submittedDate,
  archivedDate: r.archivedDate,
  restoredDate: null,
}));
